name: sepsesam api CI on ubuntu-latest

on:
  push:
    branches: [ main, github_actions ]
  pull_request:
    branches: [ main, github_actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add sesam repository key
      run: curl https://download.sep.de/linux/repositories/debian/key.asc | apt-key add -
    - name: Configure sesam apt sources
      run: echo 'deb https://download.sep.de/linux/repositories/debian/ buster main' | sudo tee -a /etc/apt/sources.list
    - name: Update apt sources
      run: apt-get update -y
    - name: Install sesam server
      run: apt-get install sesam-srv python3 -y
    - name: Execute pyunit tests
      run: python3 t/tests.py
